### ISSUE TITLE
通信证怎么获取呀

### ISSUE THREAD

**Issue by zt199510** [EmilyEdna/CandySugar#4]
通信证怎么获取呀

**Comment by EmilyEdna** [comment]
userid : emilyedna
pwd : short date with C# code

**Comment by zt199510** [comment]
一直提示网络异常是否需要vpn

**Comment by EmilyEdna** [comment]
> 一直提示网络异常是否需要vpn

这个项目我已经很久没有维护了，具体什么情况你只有自己调试了。
